In [3]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
tf.random.set_seed(1234)
model = Sequential(
    [
        tf.keras.Input(shape=(10,)),
        Dense(6, activation='sigmoid', name = 'first_layer'),
        Dense(1, activation='sigmoid', name = 'second_layer')
     ]
)

The `model.summary()` provides a description of the network:

In [13]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ first_layer (Dense)                  │ (None, 6)                   │              66 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ second_layer (Dense)                 │ (None, 1)                   │               7 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 73 (292.00 B)

 Trainable params: 73 (292.00 B)

 Non-trainable params: 0 (0.00 B)

The `get_weights()` function in Keras returns the weights and biases of a particular layer in the model.

In [25]:
W1, b1 = model.get_layer("first_layer").get_weights()
W2, b2 = model.get_layer("second_layer").get_weights()


print(f"First layer.\nsize rxc {W1.shape} \n Weights:\n", W1, f"\n size {b1.shape} \nBiases:", b1)
print(f"\n\nSecond layer.\nsize rxc {W2.shape} \n Weights:\n", W2, f"\n size {b2.shape} \nBias:", b2)

First layer.
size rxc (10, 6) 
 Weights:
 [[-0.18284214 -0.51288784 -0.4516762  -0.24889925 -0.40834093  0.57775766]
 [ 0.48872918 -0.07750386  0.26783967  0.47851926  0.6089844   0.5212236 ]
 [-0.6048826   0.35461533 -0.31379434 -0.6066333  -0.5651642   0.50396603]
 [ 0.09606135 -0.4594903   0.13635427  0.3550653   0.31815904  0.41092592]
 [-0.22921538 -0.17932394 -0.52468604 -0.07859069  0.4784544  -0.17973858]
 [-0.19663921  0.35774326 -0.07839757 -0.27645284 -0.49589944 -0.12803   ]
 [-0.05542696  0.35371596  0.581302    0.14277536  0.22506344 -0.04726487]
 [ 0.19261688  0.18025297 -0.59753144  0.44833356 -0.5316751   0.19664782]
 [ 0.2163794  -0.44367155 -0.46770066 -0.4109923   0.33359164  0.50877386]
 [ 0.17018414 -0.1093784  -0.0840767  -0.5668704   0.4618277  -0.21209708]] 
 size (6,) 
Biases: [0. 0. 0. 0. 0. 0.]


Second layer.
size rxc (6, 1) 
 Weights:
 [[ 0.1042428 ]
 [ 0.8918189 ]
 [ 0.35669327]
 [-0.83890486]
 [ 0.43915153]
 [ 0.21337616]] 
 size (1,) 
Bias: [0.]
