# Declarate data functions

In [2]:
import numpy as np

- **np.array** is a function used to create a NumPy array from an iterable object like a Python list.

In [7]:
#Using python list
data_list = [1, 2, 3, 4, 5]
array_from_list = np.array(data_list)

print(f"Array created from list: {array_from_list} and the type is {type(array_from_list)}")

Array created from list: [1 2 3 4 5] and the type is <class 'numpy.ndarray'>


- **np.zeros** is a function used to create an array filled with zeros.

In [9]:
#Using zeros function
array_zeros = np.zeros((2, 3))
print("\nArray created using zeros:")
print(array_zeros)
print(f"Type: {type(array_zeros)}")


Array created using zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
Type: <class 'numpy.ndarray'>


- **np.ones** is a function used to create an array filled with ones.

In [10]:
#Using ones function
array_ones = np.ones((3, 2))
print("\nArray created using ones:")
print(array_ones)


Array created using ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


- **np.linspace** is a function used to create an array of evenly spaced numbers over a specified interval. 

In [13]:
#Using linspace function
array_linspace = np.linspace(0, 10, 5)
print("\nArray created using linspace:")
print(array_linspace)


Array created using linspace:
[ 0.   2.5  5.   7.5 10. ]


- **np.random.rand** is a function which generates random numbers from a uniform distribution over the interval [0, 1).

In [19]:
#Using random.rand function
#Generate a 2D array of random numbers with shape (m, n)
array_random = np.random.rand(3, 3)
print("\nArray created using random.rand:")
print(array_random)


Array created using random.rand:
[[0.1683631  0.82524313 0.96492018]
 [0.3977731  0.25171044 0.96526213]
 [0.20106291 0.46533727 0.55017815]]


- **np.random.randint** is a function which generates random integers from a specified low (inclusive) to high (exclusive) range. 

In [20]:
#Using random.randint function
# Generate a 2D array of random integers between 1 and 10 with shape (m, n)
array_randint = np.random.randint(1, 10, size=(2, 3))
print("\nArray created using random.randint:")
print(array_randint)


Array created using random.randint:
[[1 2 4]
 [9 1 8]]


- **np.eye** is a function that creates a 2-dimensional array (or matrix) with diagonal elements set to 1 and off-diagonal elements set to 0.

In [27]:
#Using eye function
array_eye = np.eye(3)
print("\nArray created using eye:")
print(array_eye)
# Generate a 3x5 identity matrix
identity_matrix_3x5 = np.eye(3, 5)
print("\nArray with 3x5 matrix:")
print(identity_matrix_3x5)


Array created using eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array with 3x5 matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


- **np.full** is a function that creates a new array filled with a specified value. It allows you to create an array of any shape and fill it with a constant value.

In [28]:
#Using full function
array_full = np.full((2, 2), 7)
print("\nArray created using full:")
print(array_full)


Array created using full:
[[7 7]
 [7 7]]
